Import('env')

env.InstallFrontend(['layout.html', 'index.html', 'help.html', 'contact.html',
                     'about.html', 'submit.html', 'results_ok.html',
                     'download.html'], 'templates')
